# Generated by Django 5.2.12 on 2026-04-08 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_screener', '0002_alter_customuser_date_joined_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('screening', 'Screening'), ('shortlisted', 'Shortlisted'), ('interview', 'Interview'), ('hired', 'Hired'), ('rejected', 'Rejected')], default='applied', max_length=20),
        ),
    ]
